[package]
name = "sonic-server"
version = "1.3.0"
description = "Fast, lightweight and schema-less search backend."
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
homepage = "https://github.com/valeriansaliou/sonic"
repository = "https://github.com/valeriansaliou/sonic.git"
keywords = ["search", "query", "server", "index"]
categories = ["database-implementations", "web-programming"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>", "Baptiste Jamin <baptistejamin@gmail.com>"]

[[bin]]
name = "sonic"
path = "src/main.rs"
doc = false

[dependencies]
log = "0.4"
toml = "0.5"
clap = { version = "2.33", default-features = false }
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"
rand = "0.7"
unicode-segmentation = "1.6"
radix = "0.6"
rocksdb = { version = "0.15", features = ["zstd"] }
fst = "0.3"
fst-levenshtein = "0.2"
fst-regex = "0.2"
regex-syntax = "0.6"
twox-hash = "1.5"
byteorder = "1.3"
hashbrown = "0.9"
linked_hash_set = "0.1"
whatlang = "0.11"
regex = "1.4"

[target.'cfg(unix)'.dependencies]
nix = "0.18"
jemallocator = { version = "0.3", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["minwindef", "consoleapi"] }

[features]
default = ["alloc-jemalloc"]
alloc-jemalloc = ["jemallocator"]
benchmark = []

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
