[package]
name = "sonic-server"
version = "1.1.9"
description = "Fast, lightweight and schema-less search backend."
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
homepage = "https://github.com/valeriansaliou/sonic"
repository = "https://github.com/valeriansaliou/sonic.git"
keywords = ["search", "query", "server", "index"]
categories = ["database-implementations", "web-programming"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>", "Baptiste Jamin <baptistejamin@gmail.com>"]

[badges]
travis-ci = { repository = "valeriansaliou/sonic", branch = "master" }
coveralls = { repository = "valeriansaliou/sonic", branch = "master", service = "github" }

[[bin]]
name = "sonic"
path = "src/main.rs"
doc = false

[dependencies]
jemallocator = { version = "0.3", optional = true }
log = "0.4"
toml = "0.5"
clap = { version = "2.33", default-features = false }
lazy_static = "1.3"
serde = "1.0"
serde_derive = "1.0"
graceful = "0.1"
rand = "0.6"
unicode-segmentation = "1.2"
radix = "0.4"
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", features = ["lz4"] }
fst = "0.3"
fst-levenshtein = "0.2"
fst-regex = "0.2"
regex-syntax = "0.6"
twox-hash = "1.2"
byteorder = "1.3"
hashbrown = "0.3"
linked_hash_set = "0.1"
whatlang = "0.7"

[features]
default = ["alloc-jemalloc"]
alloc-jemalloc = ["jemallocator"]
benchmark = []

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
