name: Build current commit

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  # Run on PRs except for documentation.
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  # PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  PLATFORMS: linux/arm64/v8,linux/amd64
  IMAGE_NAME: sonic
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/master' }}

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set datestamp for image tagging
        run: |
          echo DATESTAMP=$(date +%Y.%m.%d) >> $GITHUB_ENV

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Sonic and export compiled executable
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}
          push: false
          outputs: type=local,dest=./artifacts
          target: export

      - name: Build and push ${{ env.IMAGE_NAME }} Docker image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:dev
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/${{ env.IMAGE_NAME }}:dev-${{ env.DATESTAMP }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev-${{ env.DATESTAMP }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
          target: image

      - name: "[RELEASE] Tarball build artifacts"
        run: |
          for artifact in ${{ github.workspace }}/artifacts/*; do
            platform=$(basename $artifact)
            tar cvzf ${{ github.workspace }}/artifacts/sonic-nightly-${{ env.DATESTAMP }}.$platform.tar.gz $artifact/*
          done

      - name: "[RELEASE] Publish amd64 artifact"
        uses: actions/upload-artifact@v3
        with:
          name: sonic-nightly-${{ env.DATESTAMP }} (amd64)
          path: ${{ github.workspace }}/artifacts/sonic-nightly-${{ env.DATESTAMP }}.linux_amd64.tar.gz

      - name: "[RELEASE] Publish arm64 artifact"
        uses: actions/upload-artifact@v3
        with:
          name: sonic-nightly-${{ env.DATESTAMP }} (arm64)
          path: ${{ github.workspace }}/artifacts/sonic-nightly-${{ env.DATESTAMP }}.linux_arm64.tar.gz
